version: '3'

services:
  bookstore_backend:
    build: .
    volumes:
      - .:/app
    env_file:
      - .env/backend.env
    ports:
      - 8080:8000
    image: app:django
    container_name: bookstore_backend
    command: bash -c "
            python manage.py makemigrations &&
            python manage.py migrate &&
            python manage.py runserver 0.0.0.0:8000"
    depends_on:
      - db

  db:
    image: postgres
    container_name: storeDB
    volumes:
      - ./data/db/:/var/lib/postgres/data
    environment:
      - POSTGRES_DB=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin
    depends_on:
      - db
    restart: always
    environment:
      PGADMIN_DEFAULT_EMAIL: admin@admin.com
      PGADMIN_DEFAULT_PASSWORD: root
    ports:
      - "5050:80"