version: '3'
services:
  bookstore:
    # restart: always
    build:
      context: .

    volumes:
      - .:/app
    ports:
      - "8080:8000"
    env_file:
      - ./.env/backend.env
    image: bookstore:web
    container_name: bookstore

    command: sh -c "python manage.py makemigrations &&
                    python manage.py migrate &&
                    python manage.py runserver 0.0.0.0:8000"