# Generated by Django 4.1.7 on 2023-02-26 11:22

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='BookName',
            new_name='Books',
        ),
    ]
