# Generated by Django 4.1.7 on 2023-02-26 11:25

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('books', '0002_rename_bookname_books'),
    ]

    operations = [
        migrations.RenameField(
            model_name='books',
            old_name='authr',
            new_name='author',
        ),
        migrations.RenameField(
            model_name='books',
            old_name='name',
            new_name='title',
        ),
        migrations.AddField(
            model_name='books',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='books',
            name='created_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.DO_NOTHING, to=settings.AUTH_USER_MODEL),
            preserve_default=False,
        ),
    ]
