# Generated by Django 4.1.7 on 2023-02-26 11:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0004_product_delete_books'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='slug_field',
            field=models.SlugField(default='test', max_length=256, unique=True),
            preserve_default=False,
        ),
    ]
