# Generated by Django 4.1.7 on 2023-02-26 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0007_product_description'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='image',
            field=models.ImageField(blank=True, upload_to='images/author/'),
        ),
        migrations.AddField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, upload_to='images/product'),
        ),
    ]
