# Generated by Django 4.1.7 on 2023-03-02 10:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0008_author_image_product_cover'),
    ]

    operations = [
        migrations.AddField(
            model_name='author',
            name='slug_field',
            field=models.SlugField(blank=True, max_length=256),
        ),
    ]
