# Generated by Django 4.1.7 on 2023-03-23 05:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0012_product_rating'),
    ]

    operations = [
        migrations.AddField(
            model_name='publisher',
            name='slug_field',
            field=models.SlugField(blank=True, max_length=256),
        ),
    ]
