# Generated by Django 4.1.7 on 2023-03-30 09:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0013_publisher_slug_field'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='cover',
            field=models.ImageField(blank=True, default='images/defaults/book.jpeg', upload_to='images/product'),
        ),
    ]
