# Generated by Django 4.1.7 on 2023-04-01 15:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('books', '0014_alter_product_cover'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='product',
            options={'verbose_name_plural': 'Products'},
        ),
    ]
